# Metadata for the site header and footer
title: My website
description: A website made with GitHub Pages

# Set the production website URL when previewing
baseurl: "/sample_project"

# Markdown parser and theme settings
markdown: kramdown
theme: jekyll-theme-slate
